[credentials]
OPENAI_API_KEY = "sk-proj-7xyhCaPHJGZv2xMkyX4UT3BlbkFJqFGVqHf4AYbQej399c2e"

[theme]
primaryColor = "#7289da"  # Light purple
backgroundColor = "#f2f2f2"  # Light gray
secondaryBackgroundColor = "#ffffff"  # White
textColor = "#2c3e50"  # Dark gray
font = "sans-serif"

[layout]
sidebarWidth = 300
