[credentials]
OPENAI_API_KEY = "sk-proj-9redMYHjlDMQnyRoD1BbT3BlbkFJv3Tf6U6MLV9awI6VK5cj"

[theme]
primaryColor = "#7289da"  # Light purple
backgroundColor = "#f2f2f2"  # Light gray
secondaryBackgroundColor = "#ffffff"  # White
textColor = "#2c3e50"  # Dark gray
font = "sans-serif"

[layout]
sidebarWidth = 300
